# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-29 16:57
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('longclawproducts', '0002_auto_20170219_0804'),
        ('products', '0002_remove_productvariant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='longclawproducts.Product'),
            preserve_default=False,
        ),
    ]
