# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170903_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='price',
            new_name='base_price',
        ),
    ]
