# Generated by Django 2.1.7 on 2019-03-22 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("longclaw_shipping", "0003_auto_20190322_1429"),
        ("longclaw_configuration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="shipping_origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="longclaw_shipping.Address",
            ),
        ),
    ]
