# Generated by Django 4.1.3 on 2022-11-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("longclaw_configuration", "0002_configuration_shipping_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="default_shipping_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether to enable default shipping. This essentially means you ship to all countries, not only those with configured shipping rates",  # noqa
            ),
        ),
    ]
