doc-warnings: true
max-line-length: 160
uses:
  - django
ignore-paths:
  - longclaw/basket/migrations
  - longclaw/checkout/migrations
  - longclaw/core/migrations
  - longclaw/orders/migrations
  - longclaw/products/migrations
  - longclaw/settings/migrations
  - longclaw/shipping/migrations
python-targets:
  - 2
  - 3


