# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-03 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('longclawproducts', '0002_auto_20170219_0804'),
        ('wagtailredirects', '0005_capitalizeverbose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductIndex',
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
    ]
