# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, help_text='Optional email of the customer who made the request', max_length=254, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='products.ProductVariant')),
            ],
        ),
    ]
