# Generated by Django 2.2.5 on 2019-09-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testproducts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, help_text='Optional email of the customer who made the request', max_length=254, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='testproducts.ProductVariant')),
            ],
        ),
    ]
