# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-08 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productrequests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrequest',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
