Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    
    config.vm.provider "virtualbox" do |v|
      v.name = "longclaw"
    end
    
    config.vm.provision :shell, path: "provision.sh"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "../", "/vagrant"
end
