# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclawsettings', '0003_longclawsettings_currency_html_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='longclawsettings',
            name='currency',
            field=models.CharField(default='GBP', max_length=6),
        ),
    ]
