# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclawsettings', '0004_longclawsettings_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longclawsettings',
            name='currency',
            field=models.CharField(default='GBP', help_text='The iso currency code to use for payments', max_length=6),
        ),
        migrations.AlterField(
            model_name='longclawsettings',
            name='currency_html_code',
            field=models.CharField(default='&pound;', help_text='The HTML code for the currency symbol. Used for display purposes only', max_length=12),
        ),
    ]
