# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclaworders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_rate',
            field=models.DecimalField(decimal_places=2, default=3.95, max_digits=12),
        ),
    ]
