# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclaworders', '0003_auto_20170211_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
