# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclaworders', '0005_auto_20170311_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
