# Generated by Django 3.1.3 on 2020-12-01 00:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import longclaw.coupon.utils
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount_type_stream_field', wagtail.core.fields.StreamField([('percentage', wagtail.core.blocks.StructBlock([('percentage', wagtail.core.blocks.IntegerBlock(help_text='A value between 0 and 100 which represents the percentage discount', max_value=100, min_value=0))])), ('dollar', wagtail.core.blocks.StructBlock([('dollar', wagtail.core.blocks.FloatBlock(decimal_places=2, help_text='A value with a minimum of 0 which represents a flat dollar discount amount', min_value=0))]))])),
                ('description', models.TextField(blank=True, help_text='Short description of the type of discount. e.g. "50% discount"', null=True)),
                ('infinite_redemptions', models.BooleanField(default=False, help_text='Whether or not this coupon can be used an infinite amount of times')),
                ('max_redemptions', models.IntegerField(default=1)),
                ('redemptions', models.IntegerField(default=0)),
                ('expiry_date', models.DateTimeField(default=longclaw.coupon.utils.week_from_now, help_text='This coupon will no longer work after this date/time')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_id', models.CharField(max_length=32)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('consumed_date', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
