# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('line_1', models.CharField(max_length=128)),
                ('line_2', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCountry',
            fields=[
                ('country_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('carrier', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('shipping_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='shipping.ShippingCountry')),
            ],
        ),
    ]
