# Generated by Django 2.1.7 on 2019-03-18 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("longclaw_shipping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingrate",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="longclaw_shipping.Address",
            ),
        ),
        migrations.AddField(
            model_name="shippingrate",
            name="basket_id",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
