# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_auto_20170211_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingcountry',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='shipping_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='shipping.ShippingCountry'),
        ),
    ]
