# Generated by Django 4.1.3 on 2022-11-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("longclaw_shipping", "0004_alter_shippingrateprocessor_polymorphic_ctype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
    ]
