# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('shipping', '0006_auto_20170211_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_shipping_rate', models.DecimalField(decimal_places=2, help_text='The default shipping rate for countries which have not been configured', max_digits=12)),
                ('default_shipping_carrier', models.CharField(help_text='The default shipping carrier', max_length=32)),
                ('default_shipping_enabled', models.BooleanField(default=False, help_text='Whether to enable default shipping. This essentially means you ship to all countries, not only those with configured shipping rates')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
