# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_shippingsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingsettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='ShippingSettings',
        ),
    ]
