# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCountry',
            fields=[
                ('country_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=32)),
                ('standard_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('standard_rate_carrier', models.CharField(default='Royal Mail', max_length=64)),
                ('standard_rate_description', models.CharField(default='Royal Mail standard shipping', max_length=128)),
                ('premium_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium_rate_carrier', models.CharField(default='Royal Mail', max_length=64)),
                ('premium_rate_description', models.CharField(default='Royal Mail tracked and signed for', max_length=128)),
            ],
        ),
    ]
