# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingCountry',
        ),
    ]
