# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcountry',
            name='country_name',
            field=models.CharField(default='United Kingdom', max_length=32),
            preserve_default=False,
        ),
    ]
