# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    replaces = [('longclawshipping', '0001_initial'), ('longclawshipping', '0002_auto_20170211_1706'), ('longclawshipping', '0003_auto_20170211_2129'), ('longclawshipping', '0004_auto_20170211_2132'), ('longclawshipping', '0005_auto_20170211_2138'), ('longclawshipping', '0006_auto_20170211_2149'), ('longclawshipping', '0007_shippingsettings'), ('longclawshipping', '0008_auto_20170212_1422'), ('longclawshipping', '0009_auto_20170227_2017'), ('longclawshipping', '0010_auto_20170227_2023'), ('longclawshipping', '0011_auto_20170227_2048'), ('longclawshipping', '0012_delete_shippingcountry'), ('longclawshipping', '0013_auto_20170313_0846')]

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('line_1', models.CharField(max_length=128)),
                ('line_2', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCountry',
            fields=[
                ('country_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('carrier', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('countries', django_countries.fields.CountryField(default='UK', max_length=599, multiple=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='shippingcountry',
            options={'verbose_name_plural': 'shipping countries'},
        ),
        migrations.RemoveField(
            model_name='shippingcountry',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='shippingcountry',
            name='country_name',
        ),
        migrations.AddField(
            model_name='shippingcountry',
            name='country',
            field=django_countries.fields.CountryField(default='UK', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingcountry',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShippingCountry',
        ),
    ]
