# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclawshipping', '0002_auto_20170410_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name_official', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('sort_priority', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ('-sort_priority', 'name'),
            },
        ),
        migrations.RemoveField(
            model_name='shippingrate',
            name='countries',
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='countries',
            field=models.ManyToManyField(to='longclawshipping.Country'),
        ),
    ]
