# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclawshipping', '0005_auto_20170518_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrate',
            name='name',
            field=models.CharField(help_text='Unique name to refer to this shipping rate by', max_length=32, unique=True),
        ),
    ]
