# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('longclawshipping', '0005_auto_20170211_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingcountry',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='shippingcountry',
            name='country_name',
        ),
        migrations.AddField(
            model_name='shippingcountry',
            name='country',
            field=django_countries.fields.CountryField(default='UK', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingcountry',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
        ),
    ]
