# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longclawshipping', '0008_auto_20170212_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingcountry',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='shippingcountry',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='shipping_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='longclawshipping.ShippingCountry'),
        ),
    ]
