# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclawshipping', '0009_auto_20170227_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingrate',
            name='shipping_country',
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='countries',
            field=models.ManyToManyField(related_name='shipping_rates', to='longclawshipping.ShippingCountry'),
        ),
    ]
