# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:48
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('longclawshipping', '0010_auto_20170227_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingrate',
            name='countries',
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='countries',
            field=django_countries.fields.CountryField(default='UK', max_length=599, multiple=True),
            preserve_default=False,
        ),
    ]
