# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('longclawshipping', '0011_auto_20170227_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingCountry',
        ),
    ]
