# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclawshipping', '0012_delete_shippingcountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrate',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
