# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170107_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_note',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
