# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170107_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
    ]
